### ISSUE TITLE
Poppassd always responding "500 Old password is incorrect"

### ISSUE THREAD

**Issue by arturbonnett** [kravietz/poppassd-ceti#3]
Hello!
I'm tired of looking for a solution and can not find anything! Can someone help me?
In my server, after informing the old password, the answer is always **"500 Old password is incorrect"**

Server: CentOS release 6.8 (Final) with cPanel

**Comment by kravietz** [comment]
This is most likely caused not by `poppasd` but by incorrect PAM configuration. This program relies on your operating system's PAM configuration, can you paste how it looks currently?
