### ISSUE TITLE
patches found for to "handle pam_ldap correctly"

### ISSUE THREAD

**Issue by jonasstein** [kravietz/poppassd-ceti#5]
Hi, I found a patch on
https://bugs.gentoo.org/145839
I have no clue about it and I am no user of poppassd-ceti. Just wanted to inform you.
However, your statement on the patch suggestion would be useful for the package maintainer, who will read this here too.

**Comment by kravietz** [comment]
Thanks @jonasstein I will look at the patch and try to integrate it. The code, as you may imagine, has not changed much in the last 15 years so shouldn't be too difficult :)

**Comment by kravietz** [comment]
Seems like it's working now in [CI test](https://travis-ci.org/github/kravietz/poppassd-ceti) using `expect` so if could give it a try in a real environment with LDAP and I think we'll be quite close to closing this.
